import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { Box, Container, Text } from '@chakra-ui/react'

import { AdvantageSection } from '@/components/AdvantageSection'
import { Header } from '@/components/Header'
import { HomeHeroCategories } from '@/components/HomeHeroCategories'
import { TopBar } from '@/components/TopBar'

import { Categories } from '@/types/Categories'
import { Product } from '@/types/Product'

type Props = {
  products: Product[]
  categories: Categories[]
}

export default function Home({ products, categories }: Props) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TopBar />
      <Box marginBottom='2rem'>
        <Header />
      </Box>
      <main>
        <Container size='lg'>
          <HomeHeroCategories categories={categories} />

          <AdvantageSection />
        </Container>

        <Box margin='2rem 0' width='255px'>
          <Image
            src='https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg'
            width={200}
            height={200}
            alt=''
          />
          <Text>Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops</Text>
          <Text>$ 109.95</Text>
        </Box>

        <ol>
          {products.map((product) => {
            return (
              <li key={product.id}>
                <strong>{product.title}</strong>
              </li>
            )
          })}
        </ol>
      </main>
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const products = await fetch('https://fakestoreapi.com/products').then(
    (res) => res.json()
  )
  const categories = await fetch(
    'https://fakestoreapi.com/products/categories'
  ).then((res) => res.json())

  return {
    props: { products, categories },
  }
}
