import Head from 'next/head'

import { Header } from '@/components/Header'
import { TopBar } from '@/components/TopBar'
import { Grid, GridItem } from '@chakra-ui/react'
import { GetServerSidePropsContext } from 'next'

type Product = {
  id: number
  title: string
  price: number
  description: string
  category: string
  image: string
  rating: {
    rate: number
    count: number
  }
}

type Categories =
  | 'electronics'
  | 'jewelry'
  | "men's clothing"
  | "women's clothing"

type Props = {
  products: Product[]
  categories: Categories[]
}

export default function Home({ products, categories }: Props) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <TopBar />
        <Header />

        <Grid templateColumns='540px 255px 255px' templateRows='200px 260px'>
          {categories.map((category, key) => {
            return (
              <GridItem w='100%' h='10' bg='blue.500' key={key}>
                <p>{category}</p>
              </GridItem>
            )
          })}
        </Grid>

        {/* <ol>
          {products.map((product) => {
            return (
              <li key={product.id}>
                <strong>{product.title}</strong>
              </li>
            )
          })}
        </ol> */}
      </main>
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const products = await fetch('https://fakestoreapi.com/products').then(
    (res) => res.json()
  )
  const categories = await fetch(
    'https://fakestoreapi.com/products/categories'
  ).then((res) => res.json())

  return {
    props: { products, categories },
  }
}
